name: CI - Build and Push (Manual Input)

on:
  workflow_dispatch:
    inputs:
      docker_username:
        description: 'Docker Hub Username'
        required: true
        default: 'adityajethwa7'
      docker_token:
        description: 'Docker Hub Access Token'
        required: true
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ github.event.inputs.docker_username }}
        password: ${{ github.event.inputs.docker_token }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile.prod
        push: true
        tags: |
          ${{ github.event.inputs.docker_username }}/strapi-app:latest
          ${{ github.event.inputs.docker_username }}/strapi-app:${{ github.sha }}
        cache-from: type=registry,ref=${{ github.event.inputs.docker_username }}/strapi-app:buildcache
        cache-to: type=registry,ref=${{ github.event.inputs.docker_username }}/strapi-app:buildcache,mode=max

    - name: Image Summary
      run: |
        echo "Docker image built and pushed successfully!"
        echo "Image: ${{ github.event.inputs.docker_username }}/strapi-app:latest"
        echo "Tag: ${{ github.sha }}"
