name: CI - Build and Push Docker Image

on:
  push:
    branches: [ main ]
    paths:
      - 'app/**'
      - 'Dockerfile.prod'
      - '.github/workflows/ci.yml'
  workflow_dispatch:

env:
  DOCKER_REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/strapi-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.image.outputs.tag }}
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Generate image tag
      id: image
      run: |
        BRANCH=${GITHUB_REF##*/}
        SHA=$(echo $GITHUB_SHA | cut -c1-7)
        TAG="${BRANCH}-${SHA}-$(date +%s)"
        echo "tag=${TAG}" >> $GITHUB_OUTPUT
        echo "Image will be tagged as: ${TAG}"

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.prod
        push: true
        tags: |
          ${{ env.IMAGE_NAME }}:${{ steps.image.outputs.tag }}
          ${{ env.IMAGE_NAME }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Create deployment info
      run: |
        echo "IMAGE_TAG=${{ steps.image.outputs.tag }}" > deployment-info.env
        echo "IMAGE_NAME=${{ env.IMAGE_NAME }}" >> deployment-info.env
        echo "DEPLOYMENT_TIME=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> deployment-info.env

    - name: Upload deployment info
      uses: actions/upload-artifact@v4  # Changed from v3 to v4
      with:
        name: deployment-info
        path: deployment-info.env
        retention-days: 7

    - name: Summary
      run: |
        echo "## 🚀 Docker Image Published" >> $GITHUB_STEP_SUMMARY
        echo "**Image:** \`${{ env.IMAGE_NAME }}:${{ steps.image.outputs.tag }}\`" >> $GITHUB_STEP_SUMMARY
        echo "**Also tagged as:** \`${{ env.IMAGE_NAME }}:latest\`" >> $GITHUB_STEP_SUMMARY