name: Full Deploy - Build & Deploy (Manual)

on:
  workflow_dispatch:
    inputs:
      docker_username:
        description: 'Docker Hub Username'
        required: true
        default: 'adityajethwa7'
      docker_token:
        description: 'Docker Hub Access Token'
        required: true
        type: string
      aws_access_key:
        description: 'AWS Access Key ID'
        required: true
        type: string
      aws_secret_key:
        description: 'AWS Secret Access Key'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.build.outputs.image_tag }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ github.event.inputs.docker_username }}
        password: ${{ github.event.inputs.docker_token }}

    - name: Build and push
      id: build
      run: |
        IMAGE_TAG="${{ github.event.inputs.docker_username }}/strapi-app:${{ github.sha }}"
        docker build -f Dockerfile.prod -t $IMAGE_TAG -t ${{ github.event.inputs.docker_username }}/strapi-app:latest .
        docker push $IMAGE_TAG
        docker push ${{ github.event.inputs.docker_username }}/strapi-app:latest
        echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

  deploy:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform-strapi
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ github.event.inputs.aws_access_key }}
        aws-secret-access-key: ${{ github.event.inputs.aws_secret_key }}
        aws-region: us-east-2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Deploy Infrastructure
      run: |
        cat > terraform.tfvars << EOF
        aws_region    = "us-east-2"
        instance_type = "t3.micro"
        key_name      = "strapi-key"
        docker_image  = "${{ needs.build.outputs.image_tag }}"
        EOF
        
        terraform init
        terraform apply -auto-approve

    - name: Summary
      run: |
        echo "Deployment Complete!"
        echo "URL: http://$(terraform output -raw instance_public_ip)"
