name: Deploy - Terraform (Manual Input)

on:
  workflow_dispatch:
    inputs:
      aws_access_key:
        description: 'AWS Access Key ID'
        required: true
        type: string
      aws_secret_key:
        description: 'AWS Secret Access Key'
        required: true
        type: string
      aws_region:
        description: 'AWS Region'
        required: true
        default: 'us-east-2'
      key_name:
        description: 'AWS Key Pair Name'
        required: true
        default: 'strapi-key'
      docker_image:
        description: 'Docker Image'
        required: true
        default: 'adityajethwa7/strapi-app:latest'

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform-strapi
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ github.event.inputs.aws_access_key }}
        aws-secret-access-key: ${{ github.event.inputs.aws_secret_key }}
        aws-region: ${{ github.event.inputs.aws_region }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Create terraform.tfvars
      run: |
        cat > terraform.tfvars << EOF
        aws_region    = "${{ github.event.inputs.aws_region }}"
        instance_type = "t3.micro"
        key_name      = "${{ github.event.inputs.key_name }}"
        docker_image  = "${{ github.event.inputs.docker_image }}"
        EOF

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: terraform apply -auto-approve

    - name: Get Outputs
      id: outputs
      run: |
        echo "INSTANCE_IP=$(terraform output -raw instance_public_ip)" >> $GITHUB_ENV
        echo "instance_ip=$(terraform output -raw instance_public_ip)" >> $GITHUB_OUTPUT

    - name: Deployment Summary
      run: |
        echo "# Deployment Successful!"
        echo ""
        echo "## Access Your Strapi Instance:"
        echo "- **URL**: http://${{ env.INSTANCE_IP }}"
        echo "- **Admin**: http://${{ env.INSTANCE_IP }}/admin"
        echo ""
        echo "## Instance Details:"
        echo "- **Public IP**: ${{ env.INSTANCE_IP }}"
        echo "- **Region**: ${{ github.event.inputs.aws_region }}"
        echo "- **Image**: ${{ github.event.inputs.docker_image }}"
        echo ""
        echo "Please wait 3-5 minutes for Strapi to fully initialize."
